on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@master
    - run: sudo sh test.sh
    - uses: actions/upload-artifact@v1
      with:
        name: tests
        path: image
